#!/bin/bash
# This script resizes all my windows
# I place it in /usr/local/bin/

# Terminal
WID=$(wmctrl -lp | grep 'root@htb' | cut "-d " -f1)
# Firefox
FF=$(wmctrl -lp | grep 'Firefox' | cut "-d " -f1)
# BurpSuite, finds my license name
BURP=$(wmctrl -lp | grep 'Ippsec' | cut "-d " -f1)
# I wish i did comments when i set this up. Idk.
WS=$(wmctrl -lp | grep 'ftp' | cut "-d " -f1)
# Cherry Tree
CHR=$(wmctrl -lp | grep 'Cher' | cut "-d " -f1)

wmctrl -i -r $FF -e 0,75,64,1798,936
wmctrl -i -r $WS -e 0,75,64,1798,938
wmctrl -i -r $BURP -e 0,75,64,1798,936
wmctrl -i -r $WID -e 0,75,65,1800,960
wmctrl -i -r $CHR -e 0,75,65,1798,934
